name: 'actions-python-test'
description: 'actions-python-test'
inputs:
  python-version:
    description: 'python version'
    required: true
    default: '3.11'
  poetry-version:
    description: 'poetry version'
    required: true
    default: '1.4.2'
  test-framework:
    description: 'test-framework (pytest, poetry pytest, django test)'
    required: true
    default: 'pytest'

runs:
  using: "composite"
  steps:
    
    - name: Install Python ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      with:
          python-version: ${{ inputs.python-version }}

    - name: Install Poetry
      if: ${{ inputs.test-framework }} == 'poetry pytest'
      run: |
        pipx install "poetry==${{ inputs.poetry-version }}"
        poetry install
      shell: bash

    - name: Python Build Test (poetry)
      if: ${{ inputs.test-framework }} == 'poetry pytest'
      uses: pavelzw/pytest-action@v2
      with:
        emoji: false
        verbose: false
        job-summary: false
        custom-pytest: 'poetry run pytest -vv --cache-clear'