name: 'actions-python-test'
description: 'actions-python-test'
inputs:
  python-version:
    description: 'python version'
    required: true
    default: '3.11'
  test-framework:
    description: 'test-framework (pytest, poetry pytest, django test)'
    required: true
    default: 'pytest'

runs:
  using: "composite"
  steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install dependencies (poetry)
      if: inputs.test-framework == 'poetry pytest'
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
      shell: bash

    - name: Python Build Test (poetry)
      if: inputs.test-framework == 'poetry pytest'
      uses: pavelzw/pytest-action@v2
      with:
        emoji: false
        verbose: false
        job-summary: false
        custom-pytest: 'poetry run pytest -vv --cache-clear'