name: 'actions-python-test'
description: 'actions-python-test'
inputs:
  python-version:
    description: 'python version'
    required: true
    default: '3.11'
  poetry-version:
    description: 'poetry version'
    required: false
    default: '1.4.2'
  test-framework:
    description: 'test-framework (pytest, poetry pytest, django test)'
    required: true
    default: 'pytest'

runs:
  using: "composite"
  steps:

    - name: Install Poetry
      run: pipx install "poetry==${{ inputs.poetry-version }}"
      shell: bash

    - uses: actions/setup-python@v4
      with:
          python-version: '3.11'
          cache: 'poetry'

    - run: poetry install
      shell: bash

    - name: Python Build Test (poetry)
      if: ${{ inputs.test-framework }} == 'poetry pytest'
      uses: pavelzw/pytest-action@v2
      with:
        emoji: false
        verbose: false
        job-summary: false
        custom-pytest: 'poetry run pytest -vv --cache-clear'