name: 'actions-python-test'
description: 'actions-python-test'
inputs:
  test-framework:
    description: 'test-framework (pytest, poetry pytest, django test)'
    required: true
    default: 'pytest'

  emoji:
    description: 'emoji'
    required: true
    default: false
  verbose:
    description: 'verbose'
    required: true
    default: false
  job-summary:
    description: 'job-summary'
    required: true
    default: false
  custom-pytest:
    description: 'custom-pytest'
    required: true
    default: 'pytest'

runs:
  using: "composite"
  steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: pip install pytest pytest-md pytest-emoji
      shell: bash

    - name: Python Build Test
      if: inputs.test-framework == 'poetry pytest'
      uses: pavelzw/pytest-action@v2
      with:
        emoji: true
        verbose: false
        job-summary: false
        custom-pytest: 'poetry run pytest -vv --cache-clear'