name: 'actions-python-test'
description: 'actions-python-test'
inputs:
  test-framework:  # id of input
    description: 'test-framework (pytest, unittest, djangotest)'
    required: true
    default: 'pytest'
runs:
  using: "composite"
  steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install dependencies
      run: pip install pytest pytest-md pytest-emoji
      shell: bash
    - name: Python Build Test
      if: inputs.test-framework == 'pytest'
      uses: pavelzw/pytest-action@v2
      with:
        emoji: false
        verbose: false
        job-summary: true